import Head from 'next/head';
import Image from 'next/image';

import ProfilePic from '../../public/images/profile/developer-pic-1.png';
import Layout from '../components/Layout/Layout';

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Roy Cuenca</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout customContainerStyles="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={ProfilePic}
                alt="Portfolio"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2">
              {/* TODO: Animated Text Here */}
              <h1>Turning Vision Into Reality With Code And Design. </h1>
              <p>
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default Home;
