import Head from 'next/head';

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>Home</main>
    </>
  );
};

export default Home;
