import Head from 'next/head';
import Image from 'next/image';

import { LinkArrow } from '../components/Icons/LinkArrowIcon';
import AnimatedText from '../components/AnimatedText/AnimatedText';
import ProfilePic from '../../public/images/profile/profile-pic.png';
import ButtonText from '../components/ButtonText/ButtonText';
import Layout from '../components/Layout/Layout';
import Button from '../components/Button/Button';

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Roy Cuenca</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout customContainerStyles="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={ProfilePic}
                alt="Portfolio"
                className="w-full h-auto max-w-xl"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Mobile & Frontend Developer"
                customTextStyles="!text-left"
              />
              <p className="my-4 text-base font-medium">
                Hi, I'm Roy, an experienced developer specializing in React
                Native, React, and Node. With 6+ years of expertise, I've
                excelled in mobile app development (React Native) and built
                robust web solutions (React and Node). I'm passionate about
                creating captivating user interfaces and scalable solutions.
                Excited to share my expertise at this event!
              </p>
              <div className="flex items-center self-start mt-2">
                <Button action="/cv-roycuenca.pdf" download>
                  Resume <LinkArrow className="w-6 ml-1" />
                </Button>

                <ButtonText
                  text="Contact me"
                  onPressAction="mailto:roycuencadev@gmail.com"
                />
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default Home;
