export const workExperience = [
  {
    position: 'Fullstack/Mobile Developer',
    company: 'EXO mindset',
    companyLink: 'https://exomindset.co/en/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: ' Knit: Is a mobile app developed using React Native and Nest.js. It serves as a simple file management and file sharing application, similar to LastPass or Google Drive, but with a more user-friendly interface.',
  },
  {
    position: 'Fullstack Developer',
    company: 'NaturalTH',
    companyLink: 'https://naturalth.it/en/natural-tech-house/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: 'Miii: Flutter App development to manage requests for gated communities and holiday resorts.',
  },
  {
    position: 'Fullstack Developer',
    company: 'NaturalTH',
    companyLink: 'https://naturalth.it/en/natural-tech-house/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: 'Online Doctors: PWA´s React development with Redux and Sagas. Application with 3 UI: Client, Doctor and Administrator. Used for online medical consultations and shifts/appointment management.',
  },
  {
    position: 'Fullstack Developer',
    company: 'NaturalTH',
    companyLink: 'https://naturalth.it/en/natural-tech-house/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: 'Petersen Group C: Back for Frontend (BFF)´s Node.js development, for integration of microsites (landings) with backend services. React page development for interconnection of corporate site users (CMS) with Home Banking core. Nextjs Login development.',
  },
  {
    position: 'Fullstack Developer',
    company: 'NaturalTH',
    companyLink: 'https://naturalth.it/en/natural-tech-house/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: 'Buenos Aires Government: Assistent Center Website´s React development to manage possible COVID-19 cases.',
  },
  {
    position: 'Fullstack Developer',
    company: 'NaturalTH',
    companyLink: 'https://naturalth.it/en/natural-tech-house/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: 'Telecom : Operational and Executive dashboards React development for the report of client´s network failures.',
  },
  {
    position: 'Fullstack/Mobile Developer',
    company: 'NaturalTH',
    companyLink: 'https://naturalth.it/en/natural-tech-house/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: 'Nimble: React Native development for mobile app to manage takeaways orders, delivery and table reservations in restaurants. Restaurant´s administration module React development using react-admin.',
  },
  {
    position: 'Fullstack Developer',
    company: 'NaturalTH',
    companyLink: 'https://naturalth.it/en/natural-tech-house/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: 'Jelpin: team leader in PWA(front) development (mobile first design app), This app is a marcketplace for all bussines type. Online services or any location. Is develop with Nextjs (front-pwa), Nestjs (backend) & MongoDB. ',
  },
  {
    position: 'Mobile Developer',
    company: 'NaturalTH',
    companyLink: 'https://naturalth.it/en/natural-tech-house/',
    time: '2019 - 2021',
    address: 'BA, Argentina',
    work: 'Lupacan: React Native development for mobile app. Is a solcial networck  like instgram, for pet owners, adoptions and found pets. This app is built with React Native and Redux in frontend - Node.js in Backend.',
  },
  {
    position: 'Frontend Developer',
    company: 'Cucine Studios',
    companyLink: '',
    time: '2017 - 1019',
    address: 'BA, Argentina',
    work: 'App development using React.js for admin management, rent charges, clauses, messages and meetings',
  },
  {
    position: 'Frontend Developer',
    company: 'Cucine Studios',
    companyLink: '',
    time: '2017 - 1019',
    address: 'BA, Argentina',
    work: 'Web App development using React.js to showcase products and sales. And in the Backend, we use PHP for Api services',
  },
  {
    position: 'Frontend Developer',
    company: 'PandaGraphic',
    companyLink: '',
    time: '2015 - 2017 & 2021',
    address: 'Zulia, Venezuela',
    work: 'Web and Application development using HTML, Css, Jquery. And in the Backend, we use Nodejs with Express for Api services.',
  },
];
